#!/usr/bin/env python3

"""Generate the immutable slicing-by-eight tables used by crctab.c."""

import sys
from pathlib import Path


POLYNOMIAL = 0xEDB88320
ENTRY_COUNT = 256
SLICE_COUNT = 7


def base_table():
    table = []
    for index in range(ENTRY_COUNT):
        value = index
        for _ in range(8):
            value = ((value >> 1) ^ POLYNOMIAL
                     if value & 1 else value >> 1)
        table.append(value)
    return table


def generated_text():
    base = base_table()
    previous = base
    slices = []
    for _ in range(SLICE_COUNT):
        current = [base[value & 0xFF] ^ (value >> 8)
                   for value in previous]
        slices.append(current)
        previous = current

    lines = [
        "/* Generated by tools/generate_crc32_slicing.py. */",
        f"static const uint32_t crc32_slicing[{SLICE_COUNT}][256] = {{",
    ]
    for slice_values in slices:
        lines.append("{")
        for offset in range(0, ENTRY_COUNT, 4):
            entries = ", ".join(
                f"UINT32_C(0x{value:08x})"
                for value in slice_values[offset:offset + 4]
            )
            suffix = "," if offset + 4 < ENTRY_COUNT else ""
            lines.append(f"\t{entries}{suffix}")
        lines.append("},")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main():
    if len(sys.argv) != 2:
        raise SystemExit("usage: generate_crc32_slicing.py OUTPUT")
    Path(sys.argv[1]).write_text(generated_text(), encoding="ascii")


if __name__ == "__main__":
    main()
